title: The Quilt Project
short_title: Quilt
description: >-
  The Quilt project is designed around three main goals: speed, ease of use,
  and modularity. These three pillars of Quilt combine to create a slick and
  modern modding toolchain and ecosystem.
baseurl: ""
url: ""
source: "src/"

# Social media handles
twitter_username: quilt_mc
github_username:  QuiltMC
gitlab_username: quiltmc
twitch_username: quiltmc
discord_invite: https://discord.quiltmc.org

plugins:
  - jekyll-feed

collections:
  community:
    permalink: /community/:title:output_ext
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title:output_ext
    order:
      index.md
  wiki:
    permalink: /wiki/:title:output_ext
    output: true
    order:
      index.md

defaults:
  -
    scope:
      path: ""
      type: "community"
    values:
      layout: "community-document"
    order:
      index.md
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "wiki"
    values:
      layout: "wiki-page"
  # Mark pages private until full launch
  -
    scope:
      path: "install/*"
    values:
      private: true
  -
    scope:
      path: "dev/*"
    values:
      private: true
  -
    scope:
      path: ""
      type: "wiki"
    values:
      private: true


sass:
    sass_dir: _sass
