name: Build and Deploy
on:
  push:
    branches:
      stable
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            vendor/bundle
            node_modules
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}-js-${{ hashFiles('**/yarn.lock') }}

      - name: Build
        run: |
          bundle install
          yarn
          yarn run webpack
          JEKYLL_ENV=production bundle exec jekyll build
          cp CNAME _site/CNAME

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: _site

